---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: polling
  name: polling-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polling-deployment
  template:
    metadata:
      labels:
        app: polling-deployment
    spec:
      containers:
        - name: polling-container
          image: vibhor07/polling
          imagePullPolicy: Always
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: polling-service
  labels:
    app: polling-service
spec:
  selector:
    app: polling
  ports:
  - port: 8000
    targetPort: 8000
  type: LoadBalancer